#example clouddriver local file
aws:
  enabled: true
  accounts:
    - name: default-aws-account
      accountId: "012345678901"
      regions:
        - name: us-west-2
        - name: us-east-1
    - name: example-dev
      accountId: "012345678901"
      regions:
        - name: us-east-1
        - name: us-west-2
  defaultAssumeRole: role/SpinnakerManagedProfile
